### ISSUE TITLE
Little rectangles on map, apparently names

### ISSUE THREAD

**Issue by jidanni** [hotosm/HDM-CartoCSS#293] opened 2017-11-05 17:13 UTC
Please see https://github.com/openstreetmap/openstreetmap-website/issues/1669

**Comment by yohanboniface** [comment] 2017-11-05 18:58
Thanks for the report.
Tracked by #284

**Comment by yohanboniface** [comment] 2017-11-06 07:36
cc @cquest

**Comment by cquest** [comment] 2017-11-06 07:42
Looks like missing font problem or unhandled scripts by current font set...

Is this new (caused by last week upgrades) or was there before the upgrades ?

**Comment by yohanboniface** [comment] 2017-11-06 07:50
Given the impact, I think (hope) it's new: http://www.openstreetmap.org/#map=18/24.15087/120.66270&layers=H

Funny thing, as stated by @mapmeld is the fonts are OK until zoom 11 (pregenerated levels).

**Comment by sommerluk** [comment] 2017-11-06 08:05
> Funny thing, as stated by @mapmeld is the fonts are OK until zoom 11 (pregenerated levels).

So my raw guess is also that this is a missing-font-problem on the server. If there have been changes on the server last week, that seems possible…

Note that “Unifont” has different names across different Linux distributions and distribution versions, so it’s worth the pain have both, "Unifont Medium" and "unifont Medium" in the list. (See https://github.com/gravitystorm/openstreetmap-carto/pull/429/files for details.)

**Comment by yohanboniface** [comment] 2017-11-06 08:10
> So my raw guess is also that this is a missing-font-problem on the server.

Why would the tiles be OK until zoom 11 then?

**Comment by sommerluk** [comment] 2017-11-06 08:26
Okay, I thought “pre-rendered” ment that they are not rendered on the
server…

Lukas Sommer

2017-11-06 8:10 GMT+00:00 Yohan Boniface <notifications@github.com>:

**Comment by yohanboniface** [comment] 2017-11-06 08:37
> Okay, I thought “pre-rendered” ment that they are not rendered on the server… 

Ah, nope :)
They are rendered through `render_list` script, as opposed to "on demand" for higher zoom levels (AFAIK, because I'm not running the server).

But checking the conf, it seems even the zoom 12 is supposed to be rendered, so my guess that the difference was coming from the difference generation process seems wrong.

@cquest could it be that something worked when you ran the render_list, and some later upgrade/conf change broke it? I'm on IRC if you are not on the metro ;)

**Comment by cquest** [comment] 2017-11-06 14:46
Good catch from @sommerluk it is simply a change in the font name... unifont (12.04) > Unifont (16.04)

I've changed the xml directly, and it is now ok. A few tiles need to be re-rendered...

**Comment by skorasaurus** [comment] 2017-11-06 14:55
Sounds like this can be closed now since the issue had been fixed in the code (https://github.com/hotosm/HDM-CartoCSS/commit/fd20003091d82e84c686451cda32576c1c5481bb) but had not yet been deployed, correct? 

Re-open if I am misunderstanding and thank you for the report. :)

**Closed by skorasaurus** 2017-11-06 14:55 UTC

**Comment by jidanni** [comment] 2017-11-07 12:01
I am now seeing the problem at levels 12 and 13.
http://www.openstreetmap.org/#map=12/24.1636/120.6840&layers=H
http://www.openstreetmap.org/#map=13/24.1636/120.6840&layers=H

**Comment by cquest** [comment] 2017-11-07 13:52
Still re-rendering tiles...

**Comment by jidanni** [comment] 2017-11-08 20:36
Problem still on level 12.
I can't tell if you confirm the problem is all fixed on your end as the bug is already closed.

**Comment by cquest** [comment] 2017-11-08 22:43
Zoom 12 is still rendering...
