### ISSUE TITLE
No highway labels on humanitarian map

### ISSUE THREAD

**Issue by Lonkmapp** [hotosm/HDM-CartoCSS#341] opened 2024-12-13 19:35 UTC
Can you add this so the map looks more professional  please !

**Comment by matkoniecz** [comment] 2024-12-15 10:52
duplicate of https://github.com/hotosm/HDM-CartoCSS/issues/340

**Comment by skorasaurus** [comment] 2024-12-23 23:35
Please see response at https://github.com/hotosm/HDM-CartoCSS/issues/342#issuecomment-2560430915

**Closed as completed by skorasaurus** 2024-12-23 23:35 UTC

**Comment by Lonkmapp** [comment] 2024-12-24 20:59
Oh wow so there is no way to add them in at all ?

**Comment by matkoniecz** [comment] 2024-12-25 07:39
> Oh wow so there is no way to add them in at all ?

Response in https://github.com/hotosm/HDM-CartoCSS/issues/342#issuecomment-2560430915 is saying something else.

Please reread https://github.com/hotosm/HDM-CartoCSS/issues/342#issuecomment-2560430915

**Comment by Lonkmapp** [comment] 2024-12-25 16:47
That’s truly disappointing :(
