### ISSUE TITLE
Support more scripts with Noto fonts

### ISSUE THREAD

**Issue by mapmeld** [hotosm/HDM-CartoCSS#284] opened 2016-09-22 00:01 UTC
I've seen an improvement to how Southeast Asian script labels are rendered on OpenStreetMap.org using the upgraded Mapnik (and possibly this recently merged PR to their carto style: https://github.com/gravitystorm/openstreetmap-carto/pull/2349 )

Would it be possible for the HOT style to use Noto fonts, too?

**Comment by yohanboniface** [comment] 2016-09-23 11:47
Sounds good! I'll have a deeper look :)

**Comment by yohanboniface** [comment] 2017-01-17 17:26
Just has a quick look: Noto only has four styles (regular, italic, bold, bold italic).
The issue is that we are using semi-bold a lot, so this needs a bit of design decision whether to move down to regular or up to bold for each usage.
I'll try to have a new look.

**Comment by sommerluk** [comment] 2017-08-28 09:36
The next version of Noto is in development and will have support for various weights and widths: https://github.com/googlei18n/noto-fonts/blob/master/FAQ.md#what-are-googles-plans-for-noto-so-called-phase-3 There is an alpha version available yet: https://github.com/googlei18n/noto-fonts-alpha Not sure when the final Noto Phase III will be released…

**Comment by yohanboniface** [comment] 2017-08-28 09:44
Thanks for the info!
I'll digg into this, would love to support Noto, which as broader alphabets support.

**Comment by sommerluk** [comment] 2017-08-28 17:36
Let me know if you have further questions (regarding the code for Noto in openstreetmap-carto)…

**Comment by sommerluk** [comment] 2017-09-22 10:10
With https://github.com/googlei18n/noto-fonts/pull/967 now new Noto version with various weights is released at https://github.com/googlei18n/noto-fonts (dictionaries “hinted” and “unhinted”).

**Comment by jidanni** [comment] 2017-11-06 02:45
Are you sure #293 is related? Does it have to do with Noto fonts? Isn't just showing empty boxes worse than showing the character, but just in a different font?

**Comment by jidanni** [comment] 2017-11-06 02:49
As you see, every single Chinese character is gone 
http://www.openstreetmap.org/#map=19/24.15071/120.66228&layers=H

And as this area's official language is Chinese, wouldn't that impede any rescue operations etc. making this a critical bug?

**Comment by jidanni** [comment] 2017-11-06 02:50
On the Korean example at the top of this bug page, there is plenty of Korean still visible. On my Chinese example every single last character is gone.

**Comment by mapmeld** [comment] 2017-11-06 03:08
If it helps to identify the bug - Chinese characters are still visible on zoom-11 and broken on zoom-12

**Comment by yohanboniface** [comment] 2017-11-06 07:35
OK, sorry, seems really a new bug, reopening #293

**Closed** 2018-03-21 19:57 UTC
